### ISSUE TITLE
在cmake boost的CMakeList时错误 Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by xinxing-Zhou** [System233/boost-android-prebuilt#1]
你好，我想请教一下
我在cmake boost到
include(BoostRoot)的时候报错了
BoostRoot应该定义什么内容？
![16554563058166](https://user-images.githubusercontent.com/53686423/174265112-a5e148fd-fb18-4f36-bd07-55a3145996f1.png)

**Comment by xinxing-Zhou** [comment]
找到问题了，我之前的网络太差了有部分内容克隆超时失败了，tools里的.cmake文件没有所以报错了

**Comment by xinxing-Zhou** [comment]
有个小问题build-boost.sh里的ndk路径应该要和一开始配置的环境变量一致
![image](https://user-images.githubusercontent.com/53686423/174480140-d73e24c0-5e68-4a99-a359-3954677cd5ae.png)

**Comment by System233** [comment]
确实诶，自己疏忽了
